Repository YOCOING/YOCO, pull requests merged in 2024-05, with the labels that each got.

#28 [feat] remove eslintrc.cjs
  .eslintrc.cjs
  .eslintrc.json
Labels: enhancement

#27 [Docs] CONTRIBUTING.md
  CONTRIBUTING.md
  images/contribution/compareBranch.png
Labels: documentation

#36 feat: remove few files not in use
  .vscode/extensions.json
  .yarnrc
  vsc-extension-quickstart.md
Labels: enhancement

#20 [Test] setting environment to test functional code
  .vscode-test.mjs
  .vscode/launch.json
  package.json
  src/test/extension.test.ts
  src/test/runTest.ts
  src/test/utils/extension.test.ts
  src/test/utils/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, test

#37 [chore] update description, displayname, logo image
  CONTRIBUTING.md
  README.md
  images/icon.png
  images/logo.png
  package.json
Labels: documentation

#43 [Feat] define node version
  .nvmrc
Labels: enhancement

#39 [chore] add CI and release workflow configuration
  .github/workflows/ci.yml
  .github/workflows/pr-check-version_upgrade.yml
  .github/workflows/release.yml
Labels: enhancement

#44 [Docs] issue templates change
  .github/ISSUE_TEMPLATE/✅-Feature-Request.yml
  .github/ISSUE_TEMPLATE/✅-Feature.md
  .github/ISSUE_TEMPLATE/🐞-Bug-Report.md
  .github/ISSUE_TEMPLATE/🐞-Bug-Report.yml
Labels: documentation

#50 [fix] removed comment workflow
  .github/workflows/comment.yml
Labels: bug

#53 [Fix] Release workflow configuration
  .github/workflows/release.yml
  .vscode/settings.json
Labels: enhancement

#56 [Fix] issue template not applied
  .github/ISSUE_TEMPLATE/Bug-Report.md
  .github/ISSUE_TEMPLATE/Feature-Request.md
Labels: bug

#58 [fix] remove yml
  .github/ISSUE_TEMPLATE/Bug-Report.md
  .github/ISSUE_TEMPLATE/Bug-Report.yml
  .github/ISSUE_TEMPLATE/Feature-Request.md
  .github/ISSUE_TEMPLATE/Feature-Request.yml
Labels: bug

#62 [feat] set default backticks option to false
  package.json
Labels: bug
